on:
  push:
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20.x
      - name: Install
        run: pnpm i
      - name: Build
        run: pnpm run build
        env:
          ENVIRONMENT: ci
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "index.user.js,README.md"
